### ISSUE TITLE
Release to maven repository

### ISSUE THREAD

**Issue by rohit-soni** [awslabs/aws-scala-sdk#3]
Hello david-at-aws,

We are planning to use the aws-scala-sdk to connect to DynamoDB in our scala codebase. At the moment, we are having to compile the jar locally to use it. Can you please perform a release of this module to a maven repository so that we can add that as the dependency?

Thanks

**Comment by david-at-aws** [comment]
Yep, I'll take a look at wiring that up. Thanks for the request!

**Comment by david-at-aws** [comment]
Quick update: we want to get this moved over to [awslabs](https://github.com/awslabs) before pushing it to maven central. Working on getting approval for that, hopefully should have some good news for you soon.

**Comment by david-at-aws** [comment]
Project is now on awslabs, yay. Release to Maven central coming soon.

**Comment by david-at-aws** [comment]
"Version 1.10.7" (which wraps version 1.10.7 of the AWS SDK for Java) is now available from [maven central](http://repo1.maven.org/maven2/com/amazonaws/scala/). Enjoy and/or let me know if you run into any trouble!
